services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5179:5179"   # HTTP port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5179
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    volumes:
      - ./SukoonBackend:/app/SukoonBackend
      - ~/.nuget/packages:/root/.nuget/packages:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5179/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sukoon
      POSTGRES_PASSWORD: sukoon_dev
      POSTGRES_DB: sukoon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sukoon"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis-data:
  postgres-data: 