services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5179:5179"   # HTTP port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5179
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    volumes:
      - ./SukoonBackend:/app/SukoonBackend
      - ~/.nuget/packages:/root/.nuget/packages:ro
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sukoon
      POSTGRES_PASSWORD: sukoon_dev
      POSTGRES_DB: sukoon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data: 